### ISSUE TITLE
Any way to ignore specific file paths?

### ISSUE THREAD

**Issue by izakp** [artsy/artsy-danger#18]
I would like to be able to opt-out of Danger checks on certain file paths, much like a `.gitignore` file we should be able to put a `.dangerignore` file in our repos to exclude glob'ed paths.

**Comment by orta** [comment]
Do you mean specifically for spell checking? The spellcheck plugin supports adding custom per-repo spellcheck definitions, you can see it in action on bearden:  https://github.com/artsy/bearden/blob/master/spellcheck.json

**Comment by izakp** [comment]
I mean to ignore spellchecking for any files on a given path, not the spellcheck definitions.

**Comment by orta** [comment]
Yep - that's supported, you can use the "whitelistFiles" section in the options: 

```json
{
  "ignore": ["orta", "artsy", "github", "/danger-*."],
  "whitelistFiles": ["thing.md", "next.md"]
}
```

**Comment by izakp** [comment]
👍
