### ISSUE TITLE
Disable spellcheck?

### ISSUE THREAD

**Issue by acjay** [artsy/artsy-danger#20]
I wouldn't say I'm _strongly_ in favor of this, but I'm not sure how much value it adds or whether it's worth the time to chase completeness in adding new terminology, yet it's rather distracting.

**Comment by orta** [comment]
I've barely seen it in the last week or two, are there places where it's popping up more than others?

**Comment by acjay** [comment]
Been popping up on my Markdown updates: https://github.com/artsy/auctions/pull/642

**Comment by orta** [comment]
Sounds like a good argument for https://github.com/orta/danger-plugin-spellcheck/issues/10 with:

```
{
 "ignored_files": ["/*.md"]
}
```

Which could just suppress all the md files in that repo specifically.

**Comment by orta** [comment]
Or even that that repo is an edge case full-stop and should be ignored like the analytics repos: https://github.com/artsy/artsy-danger/blob/master/peril.settings.json#L4

**Comment by acjay** [comment]
I'll probably keep it in the repos list for now. There's some code in there, although no services.
