### ISSUE TITLE
RFC: Hook commit contexts to GitHub PR/Issue labels

### ISSUE THREAD

**Issue by orta** [artsy/artsy-danger#7]
## Proposal: 

Let's say you had a commit like this:

![screen shot 2017-08-29 at 13 52 20](https://user-images.githubusercontent.com/49038/29835874-4c2e6e8a-8cc1-11e7-91bc-984837662fe8.png)

Which is the commit the format used inside GMV. Peril should look through all of the existing labels for that repo and apply any that are used inside the commit message as a `[Label]` match.

## Reasoning

This data already exists in issues and commits, so adding it here means less chore work.

## Exceptions: 

This won't fail builds, and is only additive - so no need for exceptions

**Comment by jonallured** [comment]
Another thought here:

If we're going to teach Peril how to connect labels with commits, maybe we should get that data out of the commit subject line and put it into the body, something like this:

```
Add support for searching for a location

This commit adds support for searching for a location, which is a great feature. It was challenging to work on, but once I remembered to try hard and believe in myself the code sorta fell into place.

closes #12
labels: consignments
```

I guess what I'm saying is that if Peril can parse the commit message and apply labels, then getting that noise out of the subject line seems to have value to me. Just a thought!

**Comment by orta** [comment]
![http://i0.kym-cdn.com/photos/images/newsfeed/000/538/731/0fc.gif](http://i0.kym-cdn.com/photos/images/newsfeed/000/538/731/0fc.gif)

**Comment by orta** [comment]
I started this once: https://github.com/danger/danger-js/issues/180#issuecomment-308386682
